blank_issues_enabled: true
contact_links:
  - name: Ask a Question
    url: https://github.com/rahulhaque/soketi-app-manager-filament/discussions/new?category=q-a
    about: Ask the community for help
  - name: Feature Request
    url: https://github.com/rahulhaque/soketi-app-manager-filament/discussions/new?category=ideas
    about: Share ideas for new features
